### ISSUE TITLE
Rotation Event Implementation

### ISSUE THREAD

**Issue by chunningham** [decentralized-identity/keriox#16]
Rotation events are not yet fully implemented. Section 12.2 of the paper defines their structure, which is implemented in `src/event/event_data/rotation`, however the semantics of the event type are not yet implemented.

**Comment by blelump** [comment]
Hi @chunningham , we're slowly moving forward with this along with @edytapawlak , currently mainly gathering the inputs and filling the gaps of knowledge. It may take some more time before it's ready from our side so if you're capable to go with it faster, then please go forward.

**Comment by chunningham** [comment]
unfortunately I have not had much time over the past two weeks. I would like to prioritise features for a demo with keripy at IIW on the 20th (rotation events, interaction events and validator receipts), however I also would really like to improve the documentation beyond how I left it initially :sweat_smile:

**Comment by chunningham** [comment]
closed by #18
