### ISSUE TITLE
Backhash checking

### ISSUE THREAD

**Issue by chunningham** [decentralized-identity/keriox#19]
The `IdentifierState.last` field contains a `SelfAddressingPrefix`, however it should be a `Vec<u8>` of the previous serialised event. Implementations of `EventSemantics::apply_to` (aside from inception) should perform the check `self.previous_event_hash.derivation.derive(state.last) == self.previous_event_hash

**Comment by blelump** [comment]
@edytapawlak

**Comment by chunningham** [comment]
closed by #21
