### ISSUE TITLE
Event Validation/Handling logic over EventDB

### ISSUE THREAD

**Issue by chunningham** [decentralized-identity/keriox#32]
Currently `IdentifierState` tracks the state of a single Identifier Prefix, however it is currently limited to non-delegated Identifiers and has no capacity for Event escrow or other more complex functionality.

KeriPy has [`Kever`](https://github.com/decentralized-identity/keripy/blob/master/src/keri/core/eventing.py#L388) and [`Kevery`](https://github.com/decentralized-identity/keripy/blob/master/src/keri/core/eventing.py#L836). `Kever` is analogous to a single Identifier Prefix state machine (i.e. `IdentifierState`), while `Kevery` is a general frontend over the EventDatabase which handles the receiving and state processing of all events for all Identifiers.

This task is to implement an equivalent to `Kevery` for KERIOX, which can receive any event or receipt and process it according to the state represented by the EventDatabase instance it has a reference to (also updating the state in the EventDatabase)

**Comment by edytapawlak** [comment]
If no one is working on this already, then I would like to take care of this issue.

**Comment by chunningham** [comment]
I started looking at this [on this branch](https://github.com/decentralized-identity/keriox/tree/feat/32/proc) but its not well thought through right now, am open to feedback or alternatives

**Comment by chunningham** [comment]
closed by #47 and #44  :1st_place_medal:
