### ISSUE TITLE
Updated inception extracted data set for prefix derivation

### ISSUE THREAD

**Issue by chunningham** [decentralized-identity/keriox#57]
DFS-serialization for serialized extracted data set creation posed a malleability vulnerability when weighted sig thresholds are introduced ([as explained in this PR in keripy](https://github.com/decentralized-identity/keripy/pull/66)). To maintain interop, this must be updated. The new process is as follows:
1. collect inception data into an inception event with a dummy identifier prefix which is just `#` repeated to make correct length for chosen derivation code
2. get correct version/length string from icp event
3. set verstion/length string and serialize
4. use serialization as input to prefix derivation
5. set icp identifier prefix to derived prefix

**Comment by bumblefudge** [comment]
this seems urgent to discuss-- will agenda for today's meeting (in...43 minutes)
