### ISSUE TITLE
weighted threshold multisig

### ISSUE THREAD

**Issue by chunningham** [decentralized-identity/keriox#64]
the `sith` field in establishment events can also be represented as an ordered list of fractions, which corrospond to the ordered list of keys in the key set. The processing of the signatures then includes adding the fractions for each key used and checking that the `sum >= 1`.

Example sith:
`["1/2", "1/2", "1/4", "1/4"]`

**Comment by SmithSamuelM** [comment]
It can also be a set of clauses of weights, i,e. a list of lists of weights. If any of the lists sum to 1 then the threshold is met
