### ISSUE TITLE
Update the KeyManager trait / implementation to account for potential errors (e.g. I/O).

### ISSUE THREAD

**Issue by Exulansis** [decentralized-identity/keriox#83]
The current [implementation ](https://github.com/decentralized-identity/keriox/blob/master/src/signer/mod.rs#L35)([and usage](https://github.com/decentralized-identity/keriox/blob/master/src/keri/mod.rs#L114)) of the [KeyManager trait](https://github.com/decentralized-identity/keriox/blob/master/src/signer/mod.rs#L8) assumes that getting the [current](https://github.com/decentralized-identity/keriox/blob/master/src/signer/mod.rs#L40) / [next](https://github.com/decentralized-identity/keriox/blob/master/src/signer/mod.rs#L44) public keys never fails. This is problematic for some implementations, because getting the current public key might actually fail for some reason (e.g. unreliable internet connection + a remote signing service, or some random hardware issue).

Given the current trait definition, there is no good fallback value to return in case fetching the current / next public keys errors out. Returning an empty `vec` would have unexpected implications (e.g. might accidentality signal that an identifier is being abandoned).

The proposed solution would be to update the trait definition (and the corresponding implementation) to:

```rust
pub trait KeyManager {
    fn sign(&self, msg: &[u8]) -> Result<Vec<u8>, Error>;
    fn public_key(&self) -> Result<PublicKey, Error>;
    fn next_public_key(&self) -> Result<PublicKey, Error>;
    fn rotate(&mut self) -> Result<(), Error>;
}
```
As well as update the relevant code to account for the new `Result` type when working with the KeyManager.

In addition, the [Error](https://github.com/decentralized-identity/keriox/blob/master/src/error/mod.rs#L12) enum needs to be extended with appropriate errors.

Looking forward to feedback on this issue, in case this change is welcome, I could open a PR soon.
Thank you!

**Comment by blelump** [comment]
@Exulansis we're open for a PR :-) .
